spring:
  application:
    name: budgeting
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: budgeting
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_LIQUIBASE_USER:budgeting_liquibase}
    password: ${DB_LIQUIBASE_PASS:budgeting_liquibase}
    default-schema: budgeting
